//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CRUD_Empleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpleados
    {
        public decimal cedula { get; set; }
        public string nombreEmpleado { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
    }
}
